apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-k-food
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: k-food
  template:
    metadata:
      labels:
        app: k-food
    spec:
      containers:
      - image: 992382692054.dkr.ecr.ap-northeast-2.amazonaws.com/k-food-app:latest
        name: container-k-food
        ports:
        - containerPort: 80
