apiVersion: v1
kind: Pod
metadata:
  name: fe-deploy
  labels:
    app: fe-pod
spec:
  containers:
  - name: fe-pod
    image: 34.64.204.32:5000/nginx:latest
    ports:
    - containerPort: 
---
apiVersion: v1
kind: Service
metadata:
  name: fe-svc
spec:
  type: ClusterIP
  selector:
    app: be-pod
  ports:
  - protocol: TCP
    port: 8888
    targetPort:
